import Header from "../../components/header/Header";
import { ScrollArea } from "../../components/ui/scroll-area";
import "./globals.css";
import { Inter } from "next/font/google";
import localFont from "next/font/local";

const body = localFont({
  src: "../../public/fonts/neue/NeueMontreal-Book.otf",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={body.className}>
        <Header />
        <ScrollArea className="h-screen w-full">{children}</ScrollArea>
      </body>
    </html>
  );
}
